### ISSUE TITLE
clean install causes error

### ISSUE THREAD

**Issue by Dutchboy** [sis0k0/nativescript-webpack-sass#1]
Error....

I cloned this repo.... npm i.... and npm start-android-bundle

**Comment by sis0k0** [comment]
Sorry for the inconvenience. Fixed with 92dc8d9

**Comment by Dutchboy** [comment]
:-D So far so good!!! Do you love the color rose?? (proof I got it working)

**Comment by sis0k0** [comment]
:D

**Comment by Dutchboy** [comment]
Is it possible I can reproduce your approach?... Or is it still undocumented?...

**Comment by Dutchboy** [comment]
@sis0k0 Hi Stanimira,

Again it doesn't clean-install...

The one I tried yesterday evening still works, but as soon as I'm literally copying it to another subdir, it crashes.....
So, I thought to just clone it again in that new subdir and build-android-bundle again... Crash

**Comment by sis0k0** [comment]
@Dutchboy , I've just tested it with a clean install and it works. What's the error?

**Comment by Dutchboy** [comment]
I've just now solved it.... Seems that the subdir in which you'd have the project is **not allowed** to start with a number.... It threw an error at `spawn, line x`... Just after removing the platform, `error gradlew.bat ENOENT` so I manually `tns platform remove android` and `tns platform add android`, and there I got a better error message `"project name should not begin with a number"`.... Gosh, losing so much time on a detail.... :-(

I'm totally new to webpack. I honestly hung onto jspm / systemjs for too long, stubborn. Not that the webpack thing is too far from my imagination, but, it still feels like a black box... 

**Question** - is this repo aot or jit? It still see a main.ts and a `main.aot.ts`, while when bundling I see an `ngfactory` passing by.... Oh, _no worries_, I just re-built it **after removing the main.ts**, and I again see the _girly_ football players in the emulator in **pink** .... I guess you like football as much as I do

**Comment by Dutchboy** [comment]
@sis0k0  Still, the scss changes are not recompiled to css...
Reproduce: change `$hot` to `white` in `./app/item/items.component.common.scss`
and then `npm run start-android-bundle`

Same goes for `app.css`... I thought I could delete `app.android.css` without being punished. The bundling errors on it, because it doesn't recompile the `app.android.scss` into `app.css`

Seems the same issue as [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/issues/163)
